name: 'Hello World'
description: 'Greet someone and record the time'
author: jahirfiquitiva

inputs:
  GH_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MSG:
    description: 'Commit message used while committing to the repo'
    default: ':sparkles: Update README with the recent activity and blog posts'
    required: false
  MAX_ACTIVITY_LINES:
    description: 'The maximum number of lines populated in your readme file'
    default: 5
    required: false
  ACTIVITY_TO_HTML:
    description: 'Whether to convert activity markdown to html'
    default: false
    required: false
  MAX_FEED_LINES:
    description: 'The maximum number of lines populated in your readme file'
    default: 5
    required: false
  FEED_URL:
    description: 'The RSS url to get feed from'
    required: false
  FEED_TO_HTML:
    description: 'Whether to convert blogs markdown to html'
    default: false
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
