on: [push, workflow_dispatch]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: Job to update readme
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update readme with activity and feed
        uses: ./ # Uses an action in the root directory
        id: readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          FEED_URL: 'https://jahir.dev/feed.xml'
          FEED_TO_HTML: true
          MAX_FEED_LINES: 4
